source 'https://github.com/CocoaPods/Specs.git'

target 'BUKPhotoEditViewController_Example' do
  pod 'BUKPhotoEditViewController', :path => '../'
end

target 'BUKPhotoEditViewController_Tests' do
  pod 'BUKPhotoEditViewController', :path => '../'
end
