source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BUKPhotoEditViewController_Example', :exclusive => true do
  pod 'BUKPhotoEditViewController', :path => '../'
end

target 'BUKPhotoEditViewController_Tests', :exclusive => true do
  pod 'BUKPhotoEditViewController', :path => '../'

  
end
