source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'BUKPhotoEditViewController_Example' do
  pod 'BUKPhotoEditViewController', :path => '../'
end

target 'BUKPhotoEditViewController_Tests' do
  pod 'BUKPhotoEditViewController', :path => '../'
end
